- README.md
Create a new section "Utilities" for non-plugin tools related to MapLibre.
> add sdf glyph tool

- README.md
Adds Terra Draw as a optional library that you can use with MapLibre GL JS.
> Update README.md with link to Terra Draw

- README.md
- Added plugins maintained under [MapLibre User Group Japan](https://github.com/mug-jp)
- If okay, we can add some 'starters' for each front-end frameworks (Svelte, Vue, Vite...), these are not bindings, using bare 'maplibre-gl' library. example: https://github.com/mug-jp/maplibregljs-svelte-starter
> added mug-jp plugins

- README.md
Hi,
This repos contain css for themes who are designed to mimic the actual theme with some improvements.
- light : actually 20ko-30ko minified
- support dark mode
- support CSS variables for easy optimisation.
- 
if this interests you for the community you can include it in the listing
> add maplibre-theme

- README.md
https://leafmap.org/maplibre/overview/
> Add MapLibre Python examples with Leafmap

- README.md
Added [OpenHistoricalMap](https://www.openhistoricalmap.org/) and the [maplibre-gl-dates](https://github.com/OpenHistoricalMap/maplibre-gl-dates/) plugin.
> OpenHistoricalMap, maplibre-gl-dates

- README.md
The [plotly.py](https://github.com/plotly/plotly.py) / [plotly.js](https://github.com/plotly/plotly.js) libraries (MIT) defaults to MapLibre GL JS, are thoroughly tested, and are designed specifically for analytical figure creation. Within that niche they go far beyond the feature sets of the bindings already listed in awesome-maplibre.
I also grouped the JS bindings (angular/react/vue/svelte/vanilla js) for clarity, because this pr would require adding yet another "vanilla js" top level header, and it started to become difficult to get an overview at a glance.
> Add Plotly bindings

- README.md
Hi,
Added [Kanahiro/chiitiler](https://github.com/Kanahiro/chiitiler) to the list.
chiitiler is raster tile server alternative to TileserverGL, you can see [demo](https://spatialty-io.github.io/chiitiler-demo/?stylename=gsi-std#9.63/35.5524/140.0656).
If okay, please merge this change.
> add chiitiler

- README.md
Hello every one,
I would like to propose this library for react.
I realize that it is better to join efforts and avoid creating multiple projects.
However, I had 2 problems with the existing libraries.
`react-map-gl` is compatible with MapLibre **and** MapBox, which adds an additional abstraction in all of his code base and may cause problems in the long term when the 2 projects diverge more.
react-map-components-maplibre is a framework with a lot of features, and a ton of dependencies: `mui`, `emotion`, `jspdf`, `react-color`, `d3`, `three`. a simple hello Map adds 700 kB of code which can be a problem for very small projects.
So I think that this project could be suitable for some projects because it is very light (about 30kB) and only compatible with MapLibre, therefore as close as …
> add maplibre-react-components

- README.md
related to this PR : https://github.com/maplibre/maplibre-gl-js/pull/4706
sync move plugin description has changed in the MapLibre documentation but this PR [#4707](https://github.com/maplibre/maplibre-gl-js/pull/4707) deleted the plugins.md file so that the awesome repository is the main repository for all links
this pr allows to have the change taken into account when the MapLibre-gl-js [#4707](https://github.com/maplibre/maplibre-gl-js/pull/470) will be merged
> fix sync move description

- README.md
Splitting a new section for geocoding/search plugins as reasoned in https://github.com/maplibre/maplibre-gl-js/issues/4682
Also adding MapTiler geocoding to this section
> Separate Geocoding plugins to a new section and add MapTiler geocoding plugin

- README.md
Adding a few more here. I have a few other things we should add too, but wanted to start a discussion first on organization.
The "other official projects" designation is quite confusing. For example, it includes MapLibre Navigation Android, but the Qt and Flutter packages are listed under bindings. So it's not particularly clear where the SwiftUI DSL should end up ;) (I also noticed that the iOS Navigation SDK is missing too, but will add that after we resolve the discussion points below.)
A few ideas:
1. If we are OK repeating items, it might make sense to put both these under multiple headings, as they are all (AFAIK) "official" projects, but that is not particularly useful for discovery groupings. I'm also not sure (this is a really subjective view) if "bindings" is even a very helpful …
> Add a few more projects

- README.md
Two libraries for working with MapLibre on Compose Multiplatform (like Jetpack Compose but works on additional platforms).
* https://github.com/sargunv/maplibre-compose is mine and published to maven.
* https://github.com/skamirmaps/skamirmaps is **not** mine but it was recently open sourced (not yet published to a package repository to my knowledge).
Unsure if y'all accept submissions not from the author; if not I'm happy to scope this down to just the one that's mine.
> Add Compose Multiplatform wrappers

- README.md
I'd like to propose adding the library for rendering graticule that I wrote: https://github.com/falseinput/geogrid-maplibre-gl
MIT licensed. There's no such plugin yet in the list. The only graticule rendering library that supports both mercator and globe projection 🌐.
Demo: https://codesandbox.io/p/sandbox/wizardly-leavitt-g2cx97
> Add geogrid-maplibre-gl

- README.md
versatiles is a whole toolchain for creating and displaying vector tiles on the web.
* Create vector tiles via a wrapper for shortbread and tilemaker
* Serving vector tiles via http and their own alternative to `.mbtiles` -> `.versatiles`
* Providing fonts and sprites
* Providing tiles online via their own CDN (you are allowed to use your own CDN in front of them)
* CC-0
https://versatiles.org/
> add versatiles as tile server

- README.md
Hi,
I've just released LibreGL a modern Vue plugin for integrating MapLibre into Vue apps, and I think it may be helpful for the community.
Github repo: https://github.com/themustafaomar/libregl
It has an awesome docs: https://libregl.vercel.app
And demo: https://stackblitz.com/edit/libregl
> docs(vue): add libregl package

- .github/workflows/ci.yml
Since the content of this repo is used in the docs of maplibre-gl-js and CI is checking spelling there, I added spellcheck here as well as part of this PR.
> Add spell check to this repo

- README.md
The OpenStreetMap Americana repository moved to a new organization. Initially, GitHub redirected links to the new repository, but then [a new repository](https://github.com/ZeLonewolf/openstreetmap-americana/) was created that broke the redirects: osm-americana/openstreetmap-americana#1187.
> Update links to OpenStreetMap Americana

- README.md
[geojson-map-fit-mercator](https://tristandavey.com/geojson-map-fit-mercator/) provides an algorithm to optimally fit a set of GeoJSON data inside the viewport providing a MapLibre compatible map center, zoom level and bearing.
> Add geojson-map-fit-mercator to Utilities list

- README.md
- MapLibre Compose is now a hosted project (https://github.com/maplibre/maplibre/issues/441)
- Merged the Jetpack / Multiplatform Compose lists, as every Compose Multiplatform library is also a Jetpack Compose library (jetpack compose is the android platform for multiplatform compose)
The other sections seem to put hosted projects up top, so I did the same here; happy to restore the order if desired though
> Update jetpack compose list for maplibre-compose

- README.md
Free golf app runs entirely in the browser using MapLibre GL JS. App files statically served from github.io. More information in the GitHub repository at https://github.com/bdlucas1/ace.
> Add Ace golf app

- README.md
This pull request adds the map-gl-style-switcher control to the User Interface Plugins section.
- **map-gl-style-switcher** - A customizable style switcher control for MapLibre GL JS, also has a `react-map-gl` wrapper.
- Repository: https://github.com/muimsd/map-gl-style-switcher
- Features: Customizable style switching control for MapLibre GL JS
- Additional: Includes React wrapper for use with react-map-gl
- Added to the User Interface Plugins section in appropriate alphabetical order
This addition follows the format and style of other entries in the awesome-maplibre list.
> Add map-gl-style-switcher control for customizable style switching

- README.md
I just published **Vector Tile Lab**, an interactive sandbox tool to tune vector tiles, and added it to the list.  
This project uses MapLibre, so users can try it out instantly with zero config on their local machine.  
[Repo](https://github.com/spider-hand/vector-tile-lab)
> add Vector Tile Lab
