maplibre/awesome-maplibre

- README.md
Created a new category called "Other Plugins" for `everything non-official`, feel free to rename or propose a different wording :slightly_smiling_face:
> Adding H3J-H3T and Gauge Legend

- README.md
> Add "Users" section, list Kibana

- README.md
I just finished migrating On The Go Map to MapLibre. Worked like a charm!
> Add On The Go Map

- README.md
I created a small plugin for switching raster basemaps on the map.
> maplibre-gl-basemaps plugin

- README.md
Add one example of MapLibre GL Native.
> Add Vremenar Weather

- README.md
Another example of plugin using MapLibre addProtocol.
> add PMTiles to plugins

- README.md
This PR adds a new MapLibre Storytelling template to the Utilities section.
> Add MapLibre Storytelling to Utilities

- README.md
Added maplibre-gl-measures plugin to the list of Other Plugins
> Added maplibre-gl-measures plugin

- README.md
Small corrections on product naming
> Fix product naming

- README.md
As @HarelM's request in the PR https://github.com/maplibre/maplibre-gl-js/pull/2962, I added the same information in this repo.
> doc: added svelte packages

- README.md
Add vue-maplibre-gl which provides VueJS integration
> Update README.md to include VueJS integration

- README.md
[MapBlockly](https://mapblockly.github.io) 
[MapInventor](https://mapinventor.github.io)
> Added MapBlockly and MapInventor

- README.md
[maplibre-compass-pro](https://github.com/jedluk/maplibre-compass-pro)
[demo](https://codesandbox.io/p/sandbox/peaceful-mirzakhani-tv38ck)
> Add maplibre-compass-pro plugin

- README.md
Adding the Allmaps Maplibre plugin
> Add Allmaps Maplibre

- README.md
We rewrote [Queering the Map](https://queeringthemap.com) from scratch; [open-sourcing it](https://github.com/radical-data/queering-the-map), degoogling it and making it 100x(!) quicker. MapLibre was perfect for the job ❤️🗺️❤️
> add queering the map

- README.md
This is a fork of https://github.com/razorness/vue-maplibre-gl with added features and support for maplibre-gl 4
> Add @indoorequal/vue-maplibre-gl

- README.md
https://github.com/Kanahiro/maplibre-vscode-extension
Recently I released this, could you merge this if okay ?
> add maplibre-vscode-extension

- README.md
closes #36
I did just names alphabetically without descriptions to minimize bias.
I'm sure more exist that I don't know of.
> Add providers

- README.md
https://github.com/streetcomplete/StreetComplete/releases/tag/v59.0
> Add StreetComplete

- README.md
I wrote and maintain an R package, [mapgl](https://walker-data.com/mapgl), that is an interface to MapLibre.  This PR adds it to the README if you are interested!
> Update README.md with mapgl R package

- README.md
Was gonna add Ultra, but saw that it was already added in #65. Just updating the description to reflect that it does more than just overpass.
> Update [Overpass] Ultra

- README.md
Tracestrack Maps now provides vector tiles & style.
> Add Tracestrack Maps

- README.md
Recommend the MapLibre option - similar to
https://github.com/maplibre/maplibre-gl-js/pull/5086
> Update draw plugin

- README.md
The new react-maplibre is working quite well already
https://visgl.github.io/react-maplibre/
> add react-maplibre

- README.md
> Add maperture

- README.md
Reverts maplibre/awesome-maplibre#72
will try to keep alive the mapbox compat a bit longer - it appear to work okay with globe.
> Revert "Update draw plugin"

- README.md
Add [Mountaya](https://mountaya.com) as a proud MapLibre user.
> Add Mountaya

- README.md
https://github.com/MIERUNE/svelte-maplibre-gl
> add `svelte-maplibre-gl`

- README.md
Add Flitsmeister as user of MapLibre
> Add Flitsmeister - Update README.md

- README.md
Hi, I added a reference to libre-studio under the Utilities list, as requested in issue [89](https://github.com/maplibre/awesome-maplibre/issues/89).
Thank you, 
Joao
> Added libre-studio to the Utilities list

- README.md
> Fix py maplibre links

- README.md
Adding mapforge.org as a Maplibre GL JS user.
> Adding mapforge.org

- README.md
> add mvt server

- README.md
I use MapLibreGL JS on https://wynds.com.au to power all the maps.
> Add Wynd's

- README.md
> Add maplibre-legend tool

- README.md
Another provider of free OpenMapTiles hosting.
> Add Tuiles en Liberté
